### ISSUE TITLE
fs.WriteFile needs a callback argument

### ISSUE THREAD

**Issue by jacobg** [mvanede/webpack-version-file-plugin#5]
https://github.com/mvanede/webpack-version-file-plugin/blob/e2edece622feaa07c758c7b98a7f235524e9223d/index.js#L66-L68

or else you get this error:
```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:124:9)
    at Object.fs.writeFile (fs.js:1244:14)
```

**Comment by mvanede** [comment]
Should be fixed with the change of writeFile to writefileSync

**Comment by limingth** [comment]
@mvanede  it should be writeFileSync ?  F should be capitalized
